//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treadstone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.PostImagem = new HashSet<PostImagem>();
        }
    
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public int Tipo { get; set; }
        public string Visibilidade { get; set; }
        public string Conteudo { get; set; }
        public System.Data.Entity.Spatial.DbGeography Local { get; set; }
        public System.DateTime Cadastro { get; set; }
        public string Ativo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PostImagem> PostImagem { get; set; }
    }
}
