//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treadstone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Amigos = new HashSet<Amigos>();
            this.Amigos1 = new HashSet<Amigos>();
            this.Post = new HashSet<Post>();
            this.UsuarioImagem = new HashSet<UsuarioImagem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
        public string Genero { get; set; }
        public string Idioma { get; set; }
        public string Religiao { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Site { get; set; }
        public int FotoPerfil { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public System.DateTime Cadastro { get; set; }
        public string Ativo { get; set; }
    
        public virtual ICollection<Amigos> Amigos { get; set; }
        public virtual ICollection<Amigos> Amigos1 { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<UsuarioImagem> UsuarioImagem { get; set; }
    }
}
