//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treadstone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioImagem
    {
        public int UsuarioId { get; set; }
        public int ImagemId { get; set; }
        public string Visibilidade { get; set; }
        public System.DateTime Cadastro { get; set; }
        public string Ativo { get; set; }
    
        public virtual Imagem Imagem { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
